/* DO NOT EDIT - This file is autogenerated */

#ifndef GLFUNCTIONS_H
#define GLFUNCTIONS_H

#include <stdbool.h>
#include <stddef.h>

#include "ngpu/opengl/glincludes.h"

struct glfunctions {
    void (NGPU_GL_APIENTRY *ActiveTexture)(GLenum texture);
    void (NGPU_GL_APIENTRY *AttachShader)(GLuint program, GLuint shader);
    void (NGPU_GL_APIENTRY *BeginQuery)(GLenum target, GLuint id);
    void (NGPU_GL_APIENTRY *BeginQueryEXT)(GLenum target, GLuint id);
    void (NGPU_GL_APIENTRY *BindAttribLocation)(GLuint program, GLuint index, const GLchar * name);
    void (NGPU_GL_APIENTRY *BindBuffer)(GLenum target, GLuint buffer);
    void (NGPU_GL_APIENTRY *BindBufferBase)(GLenum target, GLuint index, GLuint buffer);
    void (NGPU_GL_APIENTRY *BindBufferRange)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
    void (NGPU_GL_APIENTRY *BindFramebuffer)(GLenum target, GLuint framebuffer);
    void (NGPU_GL_APIENTRY *BindImageTexture)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
    void (NGPU_GL_APIENTRY *BindRenderbuffer)(GLenum target, GLuint renderbuffer);
    void (NGPU_GL_APIENTRY *BindTexture)(GLenum target, GLuint texture);
    void (NGPU_GL_APIENTRY *BindVertexArray)(GLuint array);
    void (NGPU_GL_APIENTRY *BlendColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
    void (NGPU_GL_APIENTRY *BlendEquation)(GLenum mode);
    void (NGPU_GL_APIENTRY *BlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
    void (NGPU_GL_APIENTRY *BlendFunc)(GLenum sfactor, GLenum dfactor);
    void (NGPU_GL_APIENTRY *BlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
    void (NGPU_GL_APIENTRY *BlitFramebuffer)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
    void (NGPU_GL_APIENTRY *BufferData)(GLenum target, GLsizeiptr size, const void * data, GLenum usage);
    void (NGPU_GL_APIENTRY *BufferStorage)(GLenum target, GLsizeiptr size, const void * data, GLbitfield flags);
    void (NGPU_GL_APIENTRY *BufferStorageEXT)(GLenum target, GLsizeiptr size, const void * data, GLbitfield flags);
    void (NGPU_GL_APIENTRY *BufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void * data);
    GLenum (NGPU_GL_APIENTRY *CheckFramebufferStatus)(GLenum target);
    void (NGPU_GL_APIENTRY *Clear)(GLbitfield mask);
    void (NGPU_GL_APIENTRY *ClearBufferfi)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
    void (NGPU_GL_APIENTRY *ClearBufferfv)(GLenum buffer, GLint drawbuffer, const GLfloat * value);
    void (NGPU_GL_APIENTRY *ClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
    GLenum (NGPU_GL_APIENTRY *ClientWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
    void (NGPU_GL_APIENTRY *ColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
    void (NGPU_GL_APIENTRY *CompileShader)(GLuint shader);
    GLuint (NGPU_GL_APIENTRY *CreateProgram)();
    GLuint (NGPU_GL_APIENTRY *CreateShader)(GLenum type);
    void (NGPU_GL_APIENTRY *CullFace)(GLenum mode);
    void (NGPU_GL_APIENTRY *DebugMessageCallback)(GLDEBUGPROC callback, const void * userParam);
    void (NGPU_GL_APIENTRY *DeleteBuffers)(GLsizei n, const GLuint * buffers);
    void (NGPU_GL_APIENTRY *DeleteFramebuffers)(GLsizei n, const GLuint * framebuffers);
    void (NGPU_GL_APIENTRY *DeleteProgram)(GLuint program);
    void (NGPU_GL_APIENTRY *DeleteQueries)(GLsizei n, const GLuint * ids);
    void (NGPU_GL_APIENTRY *DeleteQueriesEXT)(GLsizei n, const GLuint * ids);
    void (NGPU_GL_APIENTRY *DeleteRenderbuffers)(GLsizei n, const GLuint * renderbuffers);
    void (NGPU_GL_APIENTRY *DeleteShader)(GLuint shader);
    void (NGPU_GL_APIENTRY *DeleteSync)(GLsync sync);
    void (NGPU_GL_APIENTRY *DeleteTextures)(GLsizei n, const GLuint * textures);
    void (NGPU_GL_APIENTRY *DeleteVertexArrays)(GLsizei n, const GLuint * arrays);
    void (NGPU_GL_APIENTRY *DepthFunc)(GLenum func);
    void (NGPU_GL_APIENTRY *DepthMask)(GLboolean flag);
    void (NGPU_GL_APIENTRY *DetachShader)(GLuint program, GLuint shader);
    void (NGPU_GL_APIENTRY *Disable)(GLenum cap);
    void (NGPU_GL_APIENTRY *DisableVertexAttribArray)(GLuint index);
    void (NGPU_GL_APIENTRY *DispatchCompute)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
    void (NGPU_GL_APIENTRY *DrawArrays)(GLenum mode, GLint first, GLsizei count);
    void (NGPU_GL_APIENTRY *DrawArraysInstanced)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
    void (NGPU_GL_APIENTRY *DrawBuffers)(GLsizei n, const GLenum * bufs);
    void (NGPU_GL_APIENTRY *DrawElements)(GLenum mode, GLsizei count, GLenum type, const void * indices);
    void (NGPU_GL_APIENTRY *DrawElementsInstanced)(GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei instancecount);
    void (NGPU_GL_APIENTRY *EGLImageTargetTexStorageEXT)(GLenum target, GLeglImageOES image, const GLint * attrib_list);
    void (NGPU_GL_APIENTRY *EGLImageTargetTexture2DOES)(GLenum target, GLeglImageOES image);
    void (NGPU_GL_APIENTRY *Enable)(GLenum cap);
    void (NGPU_GL_APIENTRY *EnableVertexAttribArray)(GLuint index);
    void (NGPU_GL_APIENTRY *EndQuery)(GLenum target);
    void (NGPU_GL_APIENTRY *EndQueryEXT)(GLenum target);
    GLsync (NGPU_GL_APIENTRY *FenceSync)(GLenum condition, GLbitfield flags);
    void (NGPU_GL_APIENTRY *Finish)();
    void (NGPU_GL_APIENTRY *Flush)();
    void (NGPU_GL_APIENTRY *FramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
    void (NGPU_GL_APIENTRY *FramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
    void (NGPU_GL_APIENTRY *FramebufferTextureLayer)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
    void (NGPU_GL_APIENTRY *FrontFace)(GLenum mode);
    void (NGPU_GL_APIENTRY *GenBuffers)(GLsizei n, GLuint * buffers);
    void (NGPU_GL_APIENTRY *GenFramebuffers)(GLsizei n, GLuint * framebuffers);
    void (NGPU_GL_APIENTRY *GenQueries)(GLsizei n, GLuint * ids);
    void (NGPU_GL_APIENTRY *GenQueriesEXT)(GLsizei n, GLuint * ids);
    void (NGPU_GL_APIENTRY *GenRenderbuffers)(GLsizei n, GLuint * renderbuffers);
    void (NGPU_GL_APIENTRY *GenTextures)(GLsizei n, GLuint * textures);
    void (NGPU_GL_APIENTRY *GenVertexArrays)(GLsizei n, GLuint * arrays);
    void (NGPU_GL_APIENTRY *GenerateMipmap)(GLenum target);
    void (NGPU_GL_APIENTRY *GetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name);
    void (NGPU_GL_APIENTRY *GetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name);
    void (NGPU_GL_APIENTRY *GetActiveUniformBlockName)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformBlockName);
    void (NGPU_GL_APIENTRY *GetActiveUniformBlockiv)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint * params);
    void (NGPU_GL_APIENTRY *GetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei * count, GLuint * shaders);
    GLint (NGPU_GL_APIENTRY *GetAttribLocation)(GLuint program, const GLchar * name);
    void (NGPU_GL_APIENTRY *GetBooleanv)(GLenum pname, GLboolean * data);
    GLenum (NGPU_GL_APIENTRY *GetError)();
    void (NGPU_GL_APIENTRY *GetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint * params);
    void (NGPU_GL_APIENTRY *GetIntegeri_v)(GLenum target, GLuint index, GLint * data);
    void (NGPU_GL_APIENTRY *GetIntegerv)(GLenum pname, GLint * data);
    void (NGPU_GL_APIENTRY *GetInternalformativ)(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint * params);
    void (NGPU_GL_APIENTRY *GetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog);
    void (NGPU_GL_APIENTRY *GetProgramInterfaceiv)(GLuint program, GLenum programInterface, GLenum pname, GLint * params);
    GLuint (NGPU_GL_APIENTRY *GetProgramResourceIndex)(GLuint program, GLenum programInterface, const GLchar * name);
    GLint (NGPU_GL_APIENTRY *GetProgramResourceLocation)(GLuint program, GLenum programInterface, const GLchar * name);
    void (NGPU_GL_APIENTRY *GetProgramResourceName)(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei * length, GLchar * name);
    void (NGPU_GL_APIENTRY *GetProgramResourceiv)(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum * props, GLsizei count, GLsizei * length, GLint * params);
    void (NGPU_GL_APIENTRY *GetProgramiv)(GLuint program, GLenum pname, GLint * params);
    void (NGPU_GL_APIENTRY *GetQueryObjectui64v)(GLuint id, GLenum pname, GLuint64 * params);
    void (NGPU_GL_APIENTRY *GetQueryObjectui64vEXT)(GLuint id, GLenum pname, GLuint64 * params);
    void (NGPU_GL_APIENTRY *GetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint * params);
    void (NGPU_GL_APIENTRY *GetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog);
    void (NGPU_GL_APIENTRY *GetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * source);
    void (NGPU_GL_APIENTRY *GetShaderiv)(GLuint shader, GLenum pname, GLint * params);
    const GLubyte * (NGPU_GL_APIENTRY *GetString)(GLenum name);
    const GLubyte * (NGPU_GL_APIENTRY *GetStringi)(GLenum name, GLuint index);
    GLuint (NGPU_GL_APIENTRY *GetUniformBlockIndex)(GLuint program, const GLchar * uniformBlockName);
    GLint (NGPU_GL_APIENTRY *GetUniformLocation)(GLuint program, const GLchar * name);
    void (NGPU_GL_APIENTRY *GetUniformiv)(GLuint program, GLint location, GLint * params);
    void (NGPU_GL_APIENTRY *InvalidateFramebuffer)(GLenum target, GLsizei numAttachments, const GLenum * attachments);
    void (NGPU_GL_APIENTRY *LinkProgram)(GLuint program);
    void * (NGPU_GL_APIENTRY *MapBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
    void (NGPU_GL_APIENTRY *MemoryBarrier)(GLbitfield barriers);
    void (NGPU_GL_APIENTRY *PixelStorei)(GLenum pname, GLint param);
    void (NGPU_GL_APIENTRY *QueryCounter)(GLuint id, GLenum target);
    void (NGPU_GL_APIENTRY *QueryCounterEXT)(GLuint id, GLenum target);
    void (NGPU_GL_APIENTRY *ReadBuffer)(GLenum src);
    void (NGPU_GL_APIENTRY *ReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void * pixels);
    void (NGPU_GL_APIENTRY *ReleaseShaderCompiler)();
    void (NGPU_GL_APIENTRY *RenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
    void (NGPU_GL_APIENTRY *RenderbufferStorageMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
    void (NGPU_GL_APIENTRY *Scissor)(GLint x, GLint y, GLsizei width, GLsizei height);
    void (NGPU_GL_APIENTRY *ShaderBinary)(GLsizei count, const GLuint * shaders, GLenum binaryFormat, const void * binary, GLsizei length);
    void (NGPU_GL_APIENTRY *ShaderSource)(GLuint shader, GLsizei count, const GLchar *const* string, const GLint * length);
    void (NGPU_GL_APIENTRY *StencilFunc)(GLenum func, GLint ref, GLuint mask);
    void (NGPU_GL_APIENTRY *StencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask);
    void (NGPU_GL_APIENTRY *StencilMask)(GLuint mask);
    void (NGPU_GL_APIENTRY *StencilMaskSeparate)(GLenum face, GLuint mask);
    void (NGPU_GL_APIENTRY *StencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
    void (NGPU_GL_APIENTRY *StencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
    void (NGPU_GL_APIENTRY *TexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void * pixels);
    void (NGPU_GL_APIENTRY *TexImage3D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void * pixels);
    void (NGPU_GL_APIENTRY *TexParameteri)(GLenum target, GLenum pname, GLint param);
    void (NGPU_GL_APIENTRY *TexStorage2D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
    void (NGPU_GL_APIENTRY *TexStorage3D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
    void (NGPU_GL_APIENTRY *TexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void * pixels);
    void (NGPU_GL_APIENTRY *TexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * pixels);
    void (NGPU_GL_APIENTRY *Uniform1fv)(GLint location, GLsizei count, const GLfloat * value);
    void (NGPU_GL_APIENTRY *Uniform1i)(GLint location, GLint v0);
    void (NGPU_GL_APIENTRY *Uniform1iv)(GLint location, GLsizei count, const GLint * value);
    void (NGPU_GL_APIENTRY *Uniform1uiv)(GLint location, GLsizei count, const GLuint * value);
    void (NGPU_GL_APIENTRY *Uniform2fv)(GLint location, GLsizei count, const GLfloat * value);
    void (NGPU_GL_APIENTRY *Uniform2iv)(GLint location, GLsizei count, const GLint * value);
    void (NGPU_GL_APIENTRY *Uniform2uiv)(GLint location, GLsizei count, const GLuint * value);
    void (NGPU_GL_APIENTRY *Uniform3fv)(GLint location, GLsizei count, const GLfloat * value);
    void (NGPU_GL_APIENTRY *Uniform3iv)(GLint location, GLsizei count, const GLint * value);
    void (NGPU_GL_APIENTRY *Uniform3uiv)(GLint location, GLsizei count, const GLuint * value);
    void (NGPU_GL_APIENTRY *Uniform4fv)(GLint location, GLsizei count, const GLfloat * value);
    void (NGPU_GL_APIENTRY *Uniform4iv)(GLint location, GLsizei count, const GLint * value);
    void (NGPU_GL_APIENTRY *Uniform4uiv)(GLint location, GLsizei count, const GLuint * value);
    void (NGPU_GL_APIENTRY *UniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
    void (NGPU_GL_APIENTRY *UniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value);
    void (NGPU_GL_APIENTRY *UniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value);
    void (NGPU_GL_APIENTRY *UniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value);
    GLboolean (NGPU_GL_APIENTRY *UnmapBuffer)(GLenum target);
    void (NGPU_GL_APIENTRY *UseProgram)(GLuint program);
    void (NGPU_GL_APIENTRY *VertexAttribDivisor)(GLuint index, GLuint divisor);
    void (NGPU_GL_APIENTRY *VertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer);
    void (NGPU_GL_APIENTRY *Viewport)(GLint x, GLint y, GLsizei width, GLsizei height);
    void (NGPU_GL_APIENTRY *ViewportIndexedf)(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
    void (NGPU_GL_APIENTRY *WaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
};

static const struct glfunction_load_info {
    const char *name;
    size_t offset;
    bool optional;
} glfunction_load_infos[] = {
    {"glActiveTexture", offsetof(struct glfunctions, ActiveTexture), false},
    {"glAttachShader", offsetof(struct glfunctions, AttachShader), false},
    {"glBeginQuery", offsetof(struct glfunctions, BeginQuery), true},
    {"glBeginQueryEXT", offsetof(struct glfunctions, BeginQueryEXT), true},
    {"glBindAttribLocation", offsetof(struct glfunctions, BindAttribLocation), false},
    {"glBindBuffer", offsetof(struct glfunctions, BindBuffer), false},
    {"glBindBufferBase", offsetof(struct glfunctions, BindBufferBase), false},
    {"glBindBufferRange", offsetof(struct glfunctions, BindBufferRange), false},
    {"glBindFramebuffer", offsetof(struct glfunctions, BindFramebuffer), false},
    {"glBindImageTexture", offsetof(struct glfunctions, BindImageTexture), true},
    {"glBindRenderbuffer", offsetof(struct glfunctions, BindRenderbuffer), false},
    {"glBindTexture", offsetof(struct glfunctions, BindTexture), false},
    {"glBindVertexArray", offsetof(struct glfunctions, BindVertexArray), false},
    {"glBlendColor", offsetof(struct glfunctions, BlendColor), false},
    {"glBlendEquation", offsetof(struct glfunctions, BlendEquation), false},
    {"glBlendEquationSeparate", offsetof(struct glfunctions, BlendEquationSeparate), false},
    {"glBlendFunc", offsetof(struct glfunctions, BlendFunc), false},
    {"glBlendFuncSeparate", offsetof(struct glfunctions, BlendFuncSeparate), false},
    {"glBlitFramebuffer", offsetof(struct glfunctions, BlitFramebuffer), false},
    {"glBufferData", offsetof(struct glfunctions, BufferData), false},
    {"glBufferStorage", offsetof(struct glfunctions, BufferStorage), true},
    {"glBufferStorageEXT", offsetof(struct glfunctions, BufferStorageEXT), true},
    {"glBufferSubData", offsetof(struct glfunctions, BufferSubData), false},
    {"glCheckFramebufferStatus", offsetof(struct glfunctions, CheckFramebufferStatus), false},
    {"glClear", offsetof(struct glfunctions, Clear), false},
    {"glClearBufferfi", offsetof(struct glfunctions, ClearBufferfi), false},
    {"glClearBufferfv", offsetof(struct glfunctions, ClearBufferfv), false},
    {"glClearColor", offsetof(struct glfunctions, ClearColor), false},
    {"glClientWaitSync", offsetof(struct glfunctions, ClientWaitSync), false},
    {"glColorMask", offsetof(struct glfunctions, ColorMask), false},
    {"glCompileShader", offsetof(struct glfunctions, CompileShader), false},
    {"glCreateProgram", offsetof(struct glfunctions, CreateProgram), false},
    {"glCreateShader", offsetof(struct glfunctions, CreateShader), false},
    {"glCullFace", offsetof(struct glfunctions, CullFace), false},
    {"glDebugMessageCallback", offsetof(struct glfunctions, DebugMessageCallback), true},
    {"glDeleteBuffers", offsetof(struct glfunctions, DeleteBuffers), false},
    {"glDeleteFramebuffers", offsetof(struct glfunctions, DeleteFramebuffers), false},
    {"glDeleteProgram", offsetof(struct glfunctions, DeleteProgram), false},
    {"glDeleteQueries", offsetof(struct glfunctions, DeleteQueries), true},
    {"glDeleteQueriesEXT", offsetof(struct glfunctions, DeleteQueriesEXT), true},
    {"glDeleteRenderbuffers", offsetof(struct glfunctions, DeleteRenderbuffers), false},
    {"glDeleteShader", offsetof(struct glfunctions, DeleteShader), false},
    {"glDeleteSync", offsetof(struct glfunctions, DeleteSync), false},
    {"glDeleteTextures", offsetof(struct glfunctions, DeleteTextures), false},
    {"glDeleteVertexArrays", offsetof(struct glfunctions, DeleteVertexArrays), false},
    {"glDepthFunc", offsetof(struct glfunctions, DepthFunc), false},
    {"glDepthMask", offsetof(struct glfunctions, DepthMask), false},
    {"glDetachShader", offsetof(struct glfunctions, DetachShader), false},
    {"glDisable", offsetof(struct glfunctions, Disable), false},
    {"glDisableVertexAttribArray", offsetof(struct glfunctions, DisableVertexAttribArray), false},
    {"glDispatchCompute", offsetof(struct glfunctions, DispatchCompute), true},
    {"glDrawArrays", offsetof(struct glfunctions, DrawArrays), false},
    {"glDrawArraysInstanced", offsetof(struct glfunctions, DrawArraysInstanced), false},
    {"glDrawBuffers", offsetof(struct glfunctions, DrawBuffers), false},
    {"glDrawElements", offsetof(struct glfunctions, DrawElements), false},
    {"glDrawElementsInstanced", offsetof(struct glfunctions, DrawElementsInstanced), false},
    {"glEGLImageTargetTexStorageEXT", offsetof(struct glfunctions, EGLImageTargetTexStorageEXT), true},
    {"glEGLImageTargetTexture2DOES", offsetof(struct glfunctions, EGLImageTargetTexture2DOES), true},
    {"glEnable", offsetof(struct glfunctions, Enable), false},
    {"glEnableVertexAttribArray", offsetof(struct glfunctions, EnableVertexAttribArray), false},
    {"glEndQuery", offsetof(struct glfunctions, EndQuery), true},
    {"glEndQueryEXT", offsetof(struct glfunctions, EndQueryEXT), true},
    {"glFenceSync", offsetof(struct glfunctions, FenceSync), false},
    {"glFinish", offsetof(struct glfunctions, Finish), false},
    {"glFlush", offsetof(struct glfunctions, Flush), false},
    {"glFramebufferRenderbuffer", offsetof(struct glfunctions, FramebufferRenderbuffer), false},
    {"glFramebufferTexture2D", offsetof(struct glfunctions, FramebufferTexture2D), false},
    {"glFramebufferTextureLayer", offsetof(struct glfunctions, FramebufferTextureLayer), false},
    {"glFrontFace", offsetof(struct glfunctions, FrontFace), false},
    {"glGenBuffers", offsetof(struct glfunctions, GenBuffers), false},
    {"glGenFramebuffers", offsetof(struct glfunctions, GenFramebuffers), false},
    {"glGenQueries", offsetof(struct glfunctions, GenQueries), true},
    {"glGenQueriesEXT", offsetof(struct glfunctions, GenQueriesEXT), true},
    {"glGenRenderbuffers", offsetof(struct glfunctions, GenRenderbuffers), false},
    {"glGenTextures", offsetof(struct glfunctions, GenTextures), false},
    {"glGenVertexArrays", offsetof(struct glfunctions, GenVertexArrays), false},
    {"glGenerateMipmap", offsetof(struct glfunctions, GenerateMipmap), false},
    {"glGetActiveAttrib", offsetof(struct glfunctions, GetActiveAttrib), false},
    {"glGetActiveUniform", offsetof(struct glfunctions, GetActiveUniform), false},
    {"glGetActiveUniformBlockName", offsetof(struct glfunctions, GetActiveUniformBlockName), false},
    {"glGetActiveUniformBlockiv", offsetof(struct glfunctions, GetActiveUniformBlockiv), false},
    {"glGetAttachedShaders", offsetof(struct glfunctions, GetAttachedShaders), false},
    {"glGetAttribLocation", offsetof(struct glfunctions, GetAttribLocation), false},
    {"glGetBooleanv", offsetof(struct glfunctions, GetBooleanv), false},
    {"glGetError", offsetof(struct glfunctions, GetError), false},
    {"glGetFramebufferAttachmentParameteriv", offsetof(struct glfunctions, GetFramebufferAttachmentParameteriv), false},
    {"glGetIntegeri_v", offsetof(struct glfunctions, GetIntegeri_v), false},
    {"glGetIntegerv", offsetof(struct glfunctions, GetIntegerv), false},
    {"glGetInternalformativ", offsetof(struct glfunctions, GetInternalformativ), true},
    {"glGetProgramInfoLog", offsetof(struct glfunctions, GetProgramInfoLog), false},
    {"glGetProgramInterfaceiv", offsetof(struct glfunctions, GetProgramInterfaceiv), true},
    {"glGetProgramResourceIndex", offsetof(struct glfunctions, GetProgramResourceIndex), true},
    {"glGetProgramResourceLocation", offsetof(struct glfunctions, GetProgramResourceLocation), true},
    {"glGetProgramResourceName", offsetof(struct glfunctions, GetProgramResourceName), true},
    {"glGetProgramResourceiv", offsetof(struct glfunctions, GetProgramResourceiv), true},
    {"glGetProgramiv", offsetof(struct glfunctions, GetProgramiv), false},
    {"glGetQueryObjectui64v", offsetof(struct glfunctions, GetQueryObjectui64v), true},
    {"glGetQueryObjectui64vEXT", offsetof(struct glfunctions, GetQueryObjectui64vEXT), true},
    {"glGetRenderbufferParameteriv", offsetof(struct glfunctions, GetRenderbufferParameteriv), false},
    {"glGetShaderInfoLog", offsetof(struct glfunctions, GetShaderInfoLog), false},
    {"glGetShaderSource", offsetof(struct glfunctions, GetShaderSource), false},
    {"glGetShaderiv", offsetof(struct glfunctions, GetShaderiv), false},
    {"glGetString", offsetof(struct glfunctions, GetString), false},
    {"glGetStringi", offsetof(struct glfunctions, GetStringi), false},
    {"glGetUniformBlockIndex", offsetof(struct glfunctions, GetUniformBlockIndex), false},
    {"glGetUniformLocation", offsetof(struct glfunctions, GetUniformLocation), false},
    {"glGetUniformiv", offsetof(struct glfunctions, GetUniformiv), false},
    {"glInvalidateFramebuffer", offsetof(struct glfunctions, InvalidateFramebuffer), true},
    {"glLinkProgram", offsetof(struct glfunctions, LinkProgram), false},
    {"glMapBufferRange", offsetof(struct glfunctions, MapBufferRange), false},
    {"glMemoryBarrier", offsetof(struct glfunctions, MemoryBarrier), true},
    {"glPixelStorei", offsetof(struct glfunctions, PixelStorei), false},
    {"glQueryCounter", offsetof(struct glfunctions, QueryCounter), true},
    {"glQueryCounterEXT", offsetof(struct glfunctions, QueryCounterEXT), true},
    {"glReadBuffer", offsetof(struct glfunctions, ReadBuffer), false},
    {"glReadPixels", offsetof(struct glfunctions, ReadPixels), false},
    {"glReleaseShaderCompiler", offsetof(struct glfunctions, ReleaseShaderCompiler), false},
    {"glRenderbufferStorage", offsetof(struct glfunctions, RenderbufferStorage), false},
    {"glRenderbufferStorageMultisample", offsetof(struct glfunctions, RenderbufferStorageMultisample), false},
    {"glScissor", offsetof(struct glfunctions, Scissor), false},
    {"glShaderBinary", offsetof(struct glfunctions, ShaderBinary), false},
    {"glShaderSource", offsetof(struct glfunctions, ShaderSource), false},
    {"glStencilFunc", offsetof(struct glfunctions, StencilFunc), false},
    {"glStencilFuncSeparate", offsetof(struct glfunctions, StencilFuncSeparate), false},
    {"glStencilMask", offsetof(struct glfunctions, StencilMask), false},
    {"glStencilMaskSeparate", offsetof(struct glfunctions, StencilMaskSeparate), false},
    {"glStencilOp", offsetof(struct glfunctions, StencilOp), false},
    {"glStencilOpSeparate", offsetof(struct glfunctions, StencilOpSeparate), false},
    {"glTexImage2D", offsetof(struct glfunctions, TexImage2D), false},
    {"glTexImage3D", offsetof(struct glfunctions, TexImage3D), false},
    {"glTexParameteri", offsetof(struct glfunctions, TexParameteri), false},
    {"glTexStorage2D", offsetof(struct glfunctions, TexStorage2D), true},
    {"glTexStorage3D", offsetof(struct glfunctions, TexStorage3D), true},
    {"glTexSubImage2D", offsetof(struct glfunctions, TexSubImage2D), false},
    {"glTexSubImage3D", offsetof(struct glfunctions, TexSubImage3D), false},
    {"glUniform1fv", offsetof(struct glfunctions, Uniform1fv), false},
    {"glUniform1i", offsetof(struct glfunctions, Uniform1i), false},
    {"glUniform1iv", offsetof(struct glfunctions, Uniform1iv), false},
    {"glUniform1uiv", offsetof(struct glfunctions, Uniform1uiv), false},
    {"glUniform2fv", offsetof(struct glfunctions, Uniform2fv), false},
    {"glUniform2iv", offsetof(struct glfunctions, Uniform2iv), false},
    {"glUniform2uiv", offsetof(struct glfunctions, Uniform2uiv), false},
    {"glUniform3fv", offsetof(struct glfunctions, Uniform3fv), false},
    {"glUniform3iv", offsetof(struct glfunctions, Uniform3iv), false},
    {"glUniform3uiv", offsetof(struct glfunctions, Uniform3uiv), false},
    {"glUniform4fv", offsetof(struct glfunctions, Uniform4fv), false},
    {"glUniform4iv", offsetof(struct glfunctions, Uniform4iv), false},
    {"glUniform4uiv", offsetof(struct glfunctions, Uniform4uiv), false},
    {"glUniformBlockBinding", offsetof(struct glfunctions, UniformBlockBinding), false},
    {"glUniformMatrix2fv", offsetof(struct glfunctions, UniformMatrix2fv), false},
    {"glUniformMatrix3fv", offsetof(struct glfunctions, UniformMatrix3fv), false},
    {"glUniformMatrix4fv", offsetof(struct glfunctions, UniformMatrix4fv), false},
    {"glUnmapBuffer", offsetof(struct glfunctions, UnmapBuffer), false},
    {"glUseProgram", offsetof(struct glfunctions, UseProgram), false},
    {"glVertexAttribDivisor", offsetof(struct glfunctions, VertexAttribDivisor), false},
    {"glVertexAttribPointer", offsetof(struct glfunctions, VertexAttribPointer), false},
    {"glViewport", offsetof(struct glfunctions, Viewport), false},
    {"glViewportIndexedf", offsetof(struct glfunctions, ViewportIndexedf), true},
    {"glWaitSync", offsetof(struct glfunctions, WaitSync), false},
};

#endif
