# Warning: this name must stay in sync with the badges referenced in the README
name: 'build Android 🤖'

on:
  push:
    branches:
      - 'main'
      - 'staging'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  android-build:

    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm, aarch64]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install ninja-build nasm

    - name: Build
      run: |
        ./configure.py --buildtype debug --debug-opts gl vk --host Android --host-arch ${{ matrix.arch }}
        make -f Makefile.Android.${{ matrix.arch }}
        . venv/bin/ngli-activate
        meson test -C builddir/Android/${{ matrix.arch }}/libnopegl

  android-binding:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/staging' }}

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install ninja-build nasm

    - name: Build
      run: |
        android/build.sh
